// <auto-generated />
namespace Assignment_CT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class clinics1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clinics1));
        
        string IMigrationMetadata.Id
        {
            get { return "202310201014488_clinics1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
